version: 0.2

phases:
  install:
    commands:
      - echo installing nodejs
      - curl -sL https://deb.nodesource.com/setup_12.x | bash -
      - apt-get install -y nodejs
    pre-build:
      - echo installing dependencies
      - npm install
      - npm install -g @angular/cli
    build:
      - ng build --prod

artifacts:
  files:
    - "**/*"
  discard-paths: yes
  base-directory: "dist*"